version: "3.5"
services:
  crms:
    image: crms:v${BUILD_ID}
    ports:
      - "8081:8080"
    networks:
      frontend:
  upload:
    image: upload:v${BUILD_ID}
    ports:
      - "8082:8080"
    networks:
      frontend:
networks:
  frontend:
    external: true
